name: main

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths-ignore:
    - '.github/CONTRIBUTING.md'
    - '.github/FUNDING.md'
    - '.github/ISSUE_TEMPLATE.md'
    - 'docs/**'
    - '.appveyor.yml'
    - '.travis.yml'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches-ignore:
      - 'gh-pages'
    paths-ignore:
    - '.github/CONTRIBUTING.md'
    - '.github/FUNDING.md'
    - '.github/ISSUE_TEMPLATE.md'
    - 'docs/**'
    - '.appveyor.yml'
    - '.travis.yml'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        cpu_arch: [SSE2, AVX, AVX2, AVX512]
    steps:
    - uses: actions/checkout@master

    - name: Setup
      run: .\xb setup

    - name: Build
      run: .\xb build --cpu_arch=${{matrix.cpu_arch}} --target=src\xenia-app --target=tests\xenia-cpu-ppc-tests --target=src\xenia-vfs-dump

    - name: Prepare artifacts
      run: |
          robocopy build\bin\Windows\Release artifacts xenia.exe xenia-vfs-dump.exe
          robocopy . artifacts LICENSE
          if errorlevel 8 exit /b 1
          exit /b 0
      shell: cmd

    - uses: actions/upload-artifact@master
      with:
        name: xenia-canary-${{matrix.cpu_arch}}
        path: artifacts
